### ISSUE TITLE
RabbitMQ Node stop receiving message

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/cf-services-contrib-release#151]
Hi,
I am having an issue with my RabbitMQ Node and receiving messages. When I deploy a new application and queue definition the client is able to receive messages. But after a few minutes the listener stops to work. In the log I can see:
````bash
{"timestamp":1426763474.5313818,"message":"RMQaaS-Node: Sending announcement for everyone","log_level":"debug","source":"rabbit_node_default_0","data":{},"thread_id":19148920,"fiber_id":37271520,"process_id":5302,"file":"/var/vcap/packages/rabbit_node_ng/services/ng/rabbit/vendor/bundle/ruby/1.9.1/gems/vcap_services_base-0.2.5/lib/base/node.rb","lineno":395,"method":"send_node_announcement"}
{"timestamp":1426763504.533766,"message":"RMQaaS-Node: Sending announcement for everyone","log_level":"debug","source":"rabbit_node_default_0","data":{},"thread_id":19148920,"fiber_id":37271520,"process_id":5302,"file":"/var/vcap/packages/rabbit_node_ng/services/ng/rabbit/vendor/bundle/ruby/1.9.1/gems/vcap_services_base-0.2.5/lib/base/node.rb","lineno":395,"method":"send_node_announcement"}
{"timestamp":1426763534.5361283,"message":"RMQaaS-Node: Sending announcement for everyone","log_level":"debug","source":"rabbit_node_default_0","data":{},"thread_id":19148920,"fiber_id":37271520,"process_id":5302,"file":"/var/vcap/packages/rabbit_node_ng/services/ng/rabbit/vendor/bundle/ruby/1.9.1/gems/vcap_services_base-0.2.5/lib/base/node.rb","lineno":395,"method":"send_node_announcement"}
{"timestamp":1426763560.5552351,"message":"Failed to get instance 585a191d-2d7b-4748-9fbb-0405a8e2c10a varz details: Request Timeout","log_level":"warn","source":"rabbit_node_default_0","data":{},"thread_id":39549600,"fiber_id":25884980,"process_id":5302,"file":"/var/vcap/packages/rabbit_node_ng/services/ng/rabbit/lib/rabbit_service/rabbit_node.rb","lineno":189,"method":"rescue in block in varz_details"}
{"timestamp":1426763564.5374892,"message":"RMQaaS-Node: Sending announcement for everyone","log_level":"debug","source":"rabbit_node_default_0","data":{},"thread_id":19148920,"fiber_id":37271520,"process_id":5302,"file":"/var/vcap/packages/rabbit_node_ng/services/ng/rabbit/vendor/bundle/ruby/1.9.1/gems/vcap_services_base-0.2.5/lib/base/node.rb","lineno":395,"method":"send_node_announcement"}
{"timestamp":1426763565.0228906,"message":"Failed to get instance 7dd09b76-eeab-4eea-9773-9b9b469b9acc varz details: Request Timeout","log_level":"warn","source":"rabbit_node_default_0","data":{},"thread_id":39549600,"fiber_id":25884980,"process_id":5302,"file":"/var/vcap/packages/rabbit_node_ng/services/ng/rabbit/lib/rabbit_service/rabbit_node.rb","lineno":189,"method":"rescue in block in varz_details"}
`````

Restarting the instance and the application resolves the problem. Any idea what's reason behind?

```yml
service_plans:
    rabbit:
      default:
        description: "Developer, 250MB storage, 100 connections"
        free: true
        job_management:
          high_water: 230
          low_water: 20
        configuration:
          capacity: 25
          max_clients: 100
          quota_files: 4
          quota_data_size: 240
          enable_journaling: true          
          backup:
            enable: false
          lifecycle:
            enable: false
            serialization: enable
            snapshot:
              quota: 1
````
