### ISSUE TITLE
Failed to create elasticsearch service instance

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-community/cf-services-contrib-release#164]
I created three services: postgresql , mongodb and elastic search using bosh-lite, for postgresql and mongodb service, I can create service instance of them, but for elastic search service, when I execute command "cf create-service elasticsearch default es_service_instance", there is the below error:
```
Creating service instance es_intalio in org diego / space diego as admin...
FAILED
Server error, status code: 500, error code: 10001, message: Service broker error: Internal Error
```
The content of manifest file /tmp/contrib-services-warden-manifest.yml is as below
```
compilation:
  cloud_properties:
    name: random
  network: services1
  reuse_compilation_vms: true
  workers: 3
director_uuid: 9bca5701-66c0-43ee-a4d0-64813b4b5ece
jobs:
- instances: 1
  name: mongodb_gateway
  networks:
  - name: services1
    static_ips:
    - 10.244.1.2
  release: cf-services-contrib
  resource_pool: gateway_z1
  template: mongodb_gateway
- instances: 1
  name: mongodb_node
  networks:
  - name: services1
    static_ips:
    - 10.244.1.82
  persistent_disk: 8192
  properties:
    plan: default
  release: cf-services-contrib
  resource_pool: node_z1
  template: mongodb_node_ng
- instances: 1
  name: postgresql_gateway
  networks:
  - name: services1
    static_ips:
    - 10.244.1.10
  release: cf-services-contrib
  resource_pool: gateway_z1
  template: postgresql_gateway_ng
- instances: 1
  name: postgresql_node
  networks:
  - name: services1
    static_ips:
    - 10.244.1.90
  persistent_disk: 8192
  properties:
    postgresql_node:
      plan: default
  release: cf-services-contrib
  resource_pool: node_z1
  template: postgresql_node_ng
- instances: 1
  name: elasticsearch_gateway
  networks:
  - name: services1
    static_ips:
    - 10.244.1.6
  release: cf-services-contrib
  resource_pool: gateway_z1
  template: elasticsearch_gateway
- instances: 1
  name: elasticsearch_node
  networks:
  - name: services1
    static_ips:
    - 10.244.1.86
  persistent_disk: 8192
  properties:
    plan: default
  release: cf-services-contrib
  resource_pool: node_z1
  template: elasticsearch_node
meta:
  environment: cf-services-contrib
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
name: cf-services-contrib
networks:
- name: services1
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.1.0/30
    reserved:
    - 10.244.1.1
    static:
    - 10.244.1.2
  - cloud_properties:
      name: random
    range: 10.244.1.4/30
    reserved:
    - 10.244.1.5
    static:
    - 10.244.1.6
  - cloud_properties:
      name: random
    range: 10.244.1.8/30
    reserved:
    - 10.244.1.9
    static:
    - 10.244.1.10
  - cloud_properties:
      name: random
    range: 10.244.1.12/30
    reserved:
    - 10.244.1.13
    static:
    - 10.244.1.14
  - cloud_properties:
      name: random
    range: 10.244.1.16/30
    reserved:
    - 10.244.1.17
    static:
    - 10.244.1.18
  - cloud_properties:
      name: random
    range: 10.244.1.20/30
    reserved:
    - 10.244.1.21
    static:
    - 10.244.1.22
  - cloud_properties:
      name: random
    range: 10.244.1.24/30
    reserved:
    - 10.244.1.25
    static:
    - 10.244.1.26
  - cloud_properties:
      name: random
    range: 10.244.1.28/30
    reserved:
    - 10.244.1.29
    static:
    - 10.244.1.30
  - cloud_properties:
      name: random
    range: 10.244.1.32/30
    reserved:
    - 10.244.1.33
    static:
    - 10.244.1.34
  - cloud_properties:
      name: random
    range: 10.244.1.36/30
    reserved:
    - 10.244.1.37
    static:
    - 10.244.1.38
  - cloud_properties:
      name: random
    range: 10.244.1.40/30
    reserved:
    - 10.244.1.41
    static:
    - 10.244.1.42
  - cloud_properties:
      name: random
    range: 10.244.1.44/30
    reserved:
    - 10.244.1.45
    static:
    - 10.244.1.46
  - cloud_properties:
      name: random
    range: 10.244.1.48/30
    reserved:
    - 10.244.1.49
    static:
    - 10.244.1.50
  - cloud_properties:
      name: random
    range: 10.244.1.52/30
    reserved:
    - 10.244.1.53
    static:
    - 10.244.1.54
  - cloud_properties:
      name: random
    range: 10.244.1.56/30
    reserved:
    - 10.244.1.57
    static:
    - 10.244.1.58
  - cloud_properties:
      name: random
    range: 10.244.1.60/30
    reserved:
    - 10.244.1.61
    static:
    - 10.244.1.62
  - cloud_properties:
      name: random
    range: 10.244.1.64/30
    reserved:
    - 10.244.1.65
    static:
    - 10.244.1.66
  - cloud_properties:
      name: random
    range: 10.244.1.68/30
    reserved:
    - 10.244.1.69
    static:
    - 10.244.1.70
  - cloud_properties:
      name: random
    range: 10.244.1.72/30
    reserved:
    - 10.244.1.73
    static:
    - 10.244.1.74
  - cloud_properties:
      name: random
    range: 10.244.1.76/30
    reserved:
    - 10.244.1.77
    static:
    - 10.244.1.78
  - cloud_properties:
      name: random
    range: 10.244.1.80/30
    reserved:
    - 10.244.1.81
    static:
    - 10.244.1.82
  - cloud_properties:
      name: random
    range: 10.244.1.84/30
    reserved:
    - 10.244.1.85
    static:
    - 10.244.1.86
  - cloud_properties:
      name: random
    range: 10.244.1.88/30
    reserved:
    - 10.244.1.89
    static:
    - 10.244.1.90
  - cloud_properties:
      name: random
    range: 10.244.1.92/30
    reserved:
    - 10.244.1.93
    static:
    - 10.244.1.94
  - cloud_properties:
      name: random
    range: 10.244.1.96/30
    reserved:
    - 10.244.1.97
    static:
    - 10.244.1.98
  - cloud_properties:
      name: random
    range: 10.244.1.100/30
    reserved:
    - 10.244.1.101
    static:
    - 10.244.1.102
  - cloud_properties:
      name: random
    range: 10.244.1.104/30
    reserved:
    - 10.244.1.105
    static:
    - 10.244.1.106
  - cloud_properties:
      name: random
    range: 10.244.1.108/30
    reserved:
    - 10.244.1.109
    static:
    - 10.244.1.110
  - cloud_properties:
      name: random
    range: 10.244.1.112/30
    reserved:
    - 10.244.1.113
    static:
    - 10.244.1.114
  - cloud_properties:
      name: random
    range: 10.244.1.116/30
    reserved:
    - 10.244.1.117
    static:
    - 10.244.1.118
  - cloud_properties:
      name: random
    range: 10.244.1.120/30
    reserved:
    - 10.244.1.121
    static:
    - 10.244.1.122
  - cloud_properties:
      name: random
    range: 10.244.1.124/30
    reserved:
    - 10.244.1.125
    static:
    - 10.244.1.126
  - cloud_properties:
      name: random
    range: 10.244.1.128/30
    reserved:
    - 10.244.1.129
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.132/30
    reserved:
    - 10.244.1.133
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.136/30
    reserved:
    - 10.244.1.137
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.140/30
    reserved:
    - 10.244.1.141
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.144/30
    reserved:
    - 10.244.1.145
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.148/30
    reserved:
    - 10.244.1.149
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.152/30
    reserved:
    - 10.244.1.153
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.156/30
    reserved:
    - 10.244.1.157
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.160/30
    reserved:
    - 10.244.1.161
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.164/30
    reserved:
    - 10.244.1.165
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.168/30
    reserved:
    - 10.244.1.169
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.172/30
    reserved:
    - 10.244.1.173
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.176/30
    reserved:
    - 10.244.1.177
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.180/30
    reserved:
    - 10.244.1.181
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.184/30
    reserved:
    - 10.244.1.185
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.188/30
    reserved:
    - 10.244.1.189
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.192/30
    reserved:
    - 10.244.1.193
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.196/30
    reserved:
    - 10.244.1.197
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.200/30
    reserved:
    - 10.244.1.201
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.204/30
    reserved:
    - 10.244.1.205
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.208/30
    reserved:
    - 10.244.1.209
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.212/30
    reserved:
    - 10.244.1.213
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.216/30
    reserved:
    - 10.244.1.217
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.220/30
    reserved:
    - 10.244.1.221
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.224/30
    reserved:
    - 10.244.1.225
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.228/30
    reserved:
    - 10.244.1.229
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.232/30
    reserved:
    - 10.244.1.233
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.236/30
    reserved:
    - 10.244.1.237
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.240/30
    reserved:
    - 10.244.1.241
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.244/30
    reserved:
    - 10.244.1.245
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.248/30
    reserved:
    - 10.244.1.249
    static: []
  - cloud_properties:
      name: random
    range: 10.244.1.252/30
    reserved:
    - 10.244.1.253
    static: []
properties:
  cc:
    srv_api_uri: https://api.bosh-lite.com
  elasticsearch_gateway:
    cc_api_version: v2
    supported_versions:
    - "0.20"
    token: c1oudc0w
    version_aliases:
      current: "0.20"
  elasticsearch_node:
    default_version: "0.20"
    m_actions:
    - restart
    supported_versions:
    - "0.20"
  mongodb_gateway:
    cc_api_version: v2
    default_plan: default
    supported_versions:
    - "2.2"
    token: c1oudc0w
    version_aliases:
      current: "2.2"
  mongodb_node:
    default_version: "2.2"
    loopback_required: false
    m_actions:
    - restart
    max_tmp: 900
    supported_versions:
    - "2.2"
  nats:
    address: 10.244.0.6
    authorization_timeout: 5
    password: nats
    port: "4222"
    user: nats
  networks:
    apps: cf1
    management: cf1
  postgresql_gateway:
    cc_api_version: v2
    default_plan: default
    supported_versions:
    - "9.3"
    token: c1oudc0w
    version_aliases:
      current: "9.3"
  postgresql_node:
    default_version: "9.3"
    m_actions:
    - restart
    max_tmp: 900
    password: c1oudc0w
    supported_versions:
    - "9.3"
  service_plans:
    elasticsearch:
      default:
        configuration:
          capacity: 125
        description: Developer
        free: true
        job_management:
          high_water: 230
          low_water: 20
    mongodb:
      default:
        configuration:
          backup:
            enable: true
          capacity: 125
          enable_journaling: true
          lifecycle:
            enable: true
            serialization: enable
            snapshot:
              quota: 1
          max_clients: 10
          quota_data_size: 240
          quota_files: 4
        description: Developer, shared VM, 250MB storage, 10 connections
        free: true
        job_management:
          high_water: 230
          low_water: 20
    postgresql:
      default:
        configuration:
          backup:
            enable: false
          capacity: 125
          enable_journaling: true
          lifecycle:
            enable: false
            serialization: enable
            snapshot:
              quota: 1
          max_clients: 10
          quota_data_size: 240
          quota_files: 4
        description: Developer, 250MB storage, 10 connections
        free: true
        job_management:
          high_water: 230
          low_water: 20
  uaa_client_auth_credentials:
    password: admin
    username: admin
  uaa_client_id: cf
  uaa_endpoint: http://uaa.bosh-lite.com
releases:
- name: cf-services-contrib
  version: latest
resource_pools:
- cloud_properties:
    name: random
  name: gateway_z1
  network: services1
  size: 3
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    name: random
  name: node_z1
  network: services1
  size: 3
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-180000
```
