### ISSUE TITLE
Set provider/name on gateways

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cf-services-contrib-release#30]
Add the following into all gateway.yml.erb:

```
service:
...
  provider: contrib
  provider_name: 'Community Contrib'
```
