### ISSUE TITLE
Consistent schema for selection of plan in node job

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cf-services-contrib-release#66]
In postgresql node (and the mysql node, as decided by pivotal staff when they were refactoring it):

``` yaml
    properties:
      postgresql_node:
        plan: default
```

But in other nodes:

``` yaml
    properties:
      plan: default
```

Make these two consistent.

Perhaps when the mysql job moves into this repo we can revert their change and go back to the simple 2nd option.
