### ISSUE TITLE
high_water/low_water are not used but required; provide defaults so configuration can be simplified

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cf-services-contrib-release#68]
Currently you must specify high_water & low_water config:

``` yaml
  service_plans:
    postgresql:
      default:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          lifecycle:
            enable: false
```

Since these values aren't used, modify each `*_gateway.yml.erb` to insert some arbitrary default values (250, 100) if `job_management` isn't mentioned in config.
