### ISSUE TITLE
Allow for properties.service_plans to be a simple list of service labels

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cf-services-contrib-release#70]
Currently, must provide nested set of arbitrary config to enable a service (with no lifecycle):

``` yaml
service_plans:
    postgresql:
      default:
        job_management:
          high_water: 1400
          low_water: 100
        configuration:
          lifecycle:
            enable: false
```

If no lifecycle is required (backups), then allow:

``` yaml
service_plans:
  - postgresql
```
