### ISSUE TITLE
Error 400007: `services_contrib_gateway/0' is not running after update

### ISSUE THREAD

**Issue by wulonghui** [cloudfoundry-community/cf-services-contrib-release#84]
## yml:

name: cf-services-contrib  
director_uuid: ee4cfde0-aabf-4172-add4-afb14cb7d110   # CHANGE  

releases:  
- name: cf-services-contrib  
  version: latest  

compilation:  
  workers: 3  
  network: default  
  reuse_compilation_vms: true  
  cloud_properties:  
    instance_type: m1.medium # CHANGE  

update:  
  canaries: 1  
  canary_watch_time: 30000-60000  
  update_watch_time: 30000-60000  
  max_in_flight: 4  
  max_errors: 1  

networks:  
- name: floating  
  type: vip  
  cloud_properties: {}  
- name: default  
  type: dynamic  
  cloud_properties:  
    security_groups:  
      - default 
    net_id: 4e310fd2-910d-41e5-99fa-e4f734fcbdd9 # CHANGE 

resource_pools:  
- name: small  
  network: default  
  size: 8  
  stemcell:  
    name: bosh-stemcell  
    version: latest  
  cloud_properties:  
    instance_type: m1.small # CHANGE  

jobs:  
- name: services_contrib_gateway  
  release: cf-services-contrib  
  template:  
  - elasticsearch_gateway  
  - mongodb_gateway  
  - memcached_gateway  
  - postgresql_gateway_ng  
  - redis_gateway  
  - rabbit_gateway  
  - vblob_gateway  
    instances: 1  
    resource_pool: small  
    networks:  
  - name: default  
    default: [dns, gateway]  
    properties:  
    uaa_client_id: "cf"  
    uaa_endpoint: http://uaa.mycloud.com # CHANGE  
    uaa_client_auth_credentials:  
      username: services  
      password: "c1oudc0w" # CHANGE  
- name: mongodb_service_node  
  release: cf-services-contrib  
  template: mongodb_node_ng  
  instances: 1  
  resource_pool: small  
  persistent_disk: 4096  
  properties:  
    plan: default  
  networks:  
  - name: default  
    default: [dns, gateway]  
- name: memcached_service_node  
  release: cf-services-contrib  
  template: memcached_node_ng  
  instances: 1  
  resource_pool: small  
  persistent_disk: 4096  
  properties:  
    plan: default  
  networks:  
  - name: default  
    default: [dns, gateway]  
- name: vblob_service_node  
  release: cf-services-contrib  
  template: vblob_node_ng  
  instances: 1  
  resource_pool: small  
  persistent_disk: 4096  
  properties:  
    plan: default  
  networks:  
  - name: default  
    default: [dns, gateway]  
- name: elasticsearch_service_node  
  release: cf-services-contrib  
  template: elasticsearch_node  
  instances: 1  
  resource_pool: small  
  persistent_disk: 4096  
  properties:  
    plan: "free"  
  networks:  
  - name: default  
    default: [dns, gateway]  
- name: postgresql_service_node  
  release: cf-services-contrib  
  template: postgresql_node_ng  
  instances: 1  
  resource_pool: small  
  persistent_disk: 4096  
  properties:  
    postgresql_node:  
      plan: default  
  networks:  
  - name: default  
    default: [dns, gateway]  
- name: redis_service_node  
  release: cf-services-contrib  
  template: redis_node_ng  
  instances: 1  
  resource_pool: small  
  persistent_disk: 4096  
  properties:  
    plan: default  
  networks:  
  - name: default  
    default: [dns, gateway]  
- name: rabbit_service_node  
  release: cf-services-contrib  
  template: rabbit_node_ng  
  instances: 1  
  resource_pool: small  
  persistent_disk: 4096  
  properties:  
    plan: default  
  networks:  
  - name: default  
    default: [dns, gateway]  

properties:  
  nats:  
    address: 0.core.default.cf.bosh  
    port: 4222  
    user: nats  
    password: "c1oudc0w"  
    authorization_timeout: 5  

  networks:  
    apps: default  
    management: default  

  cc:  
    srv_api_uri: http://api.mycloud.com #CHANGE  

  service_plans:  
    mongodb:  
      default:  
        description: "Developer, shared VM, 250MB storage, 10 connections"  
        free: true  
        job_management:  
          high_water: 230  
          low_water: 20  
        configuration:  
          capacity: 125  
          max_clients: 10  
          quota_files: 4  
          quota_data_size: 240  
          enable_journaling: true  
          backup:  
            enable: true  
          lifecycle:  
            enable: true  
            serialization: enable  
            snapshot:  
              quota: 1  

```
memcached:  
  default:  
    description: "Developer"  
    free: true  
    job_management:  
      high_water: 230  
      low_water: 20  
    configuration:  
      capacity: 125  

vblob:  
  default:  
    description: "Developer"  
    free: true  
    job_management:  
      high_water: 230  
      low_water: 20  
    configuration:  
      capacity: 125  

elasticsearch:  
  "free":  
    description: "Developer"  
    free: true  
    job_management:  
      high_water: 230  
      low_water: 20  
    configuration:  
      capacity: 125  

postgresql:  
  default:  
    description: "Developer, 250MB storage, 10 connections"  
    free: true  
    job_management:  
      high_water: 230  
      low_water: 20  
    configuration:  
      capacity: 125  
      max_clients: 10  
      quota_files: 4  
      quota_data_size: 240  
      enable_journaling: true  
      backup:  
        enable: false  
      lifecycle:  
        enable: false  
        serialization: enable  
        snapshot:  
          quota: 1  

redis:  
  default:  
    description: "Developer, 250MB storage, 10 connections"  
    free: true  
    job_management:  
      high_water: 230  
      low_water: 20  
    configuration:  
      capacity: 125  
      max_clients: 10  
      quota_files: 4  
      quota_data_size: 240  
      enable_journaling: true  
      backup:  
        enable: false  
      lifecycle:  
        enable: false  
        serialization: enable  
        snapshot:  
          quota: 1  


rabbit:  
  default:  
    description: "Developer, 250MB storage, 10 connections"  
    free: true  
    job_management:  
      high_water: 230  
      low_water: 20  
    configuration:  
      capacity: 125  
      max_clients: 10  
      quota_files: 4  
      quota_data_size: 240  
      enable_journaling: true  
      backup:  
        enable: false  
      lifecycle:  
        enable: false  
        serialization: enable  
        snapshot:  
          quota: 1  
```

  mongodb_gateway:  
    token: "c1oudc0w" # CHANGE - the token you use later with `cf create-service-auth-token`  
    default_plan: default  
    supported_versions: ["2.2"]  
    version_aliases:  
      current: "2.2"  
    cc_api_version: v2  
  mongodb_node:  
    supported_versions: ["2.2"]  
    default_version: "2.2"  
    max_tmp: 900  

  memcached_gateway:  
    token: "c1oudc0w"  # CHANGE - the token you use later with `cf create-service-auth-token`  
    supported_versions: ["1.4"]  
    version_aliases:  
      current: "1.4"  
    cc_api_version: v2  
  memcached_node:  
    supported_versions: ["1.4"]  
    default_version: "1.4"  

  vblob_gateway:  
    token: "c1oudc0w"  # CHANGE - the token you use later with `cf create-service-auth-token`  
    supported_versions: ["0.51"]  
    version_aliases:  
      current: "0.51"  
    cc_api_version: v2  
  vblob_node:  
    supported_versions: ["0.51"]  
    default_version: "0.51"  

  elasticsearch_gateway:  
    token: "c1oudc0w"  # CHANGE - the token you use later with `cf create-service-auth-token`  
    supported_versions: ["0.20"]  
    version_aliases:  
      current: "0.20"  
    cc_api_version: v2  
  elasticsearch_node:  
    supported_versions: ["0.20"]  
    default_version: "0.20"  

  postgresql_gateway:  
    token: "c1oudc0w"  # CHANGE - the token you use later with `cf create-service-auth-token`  
    default_plan: default  
    supported_versions: ["9.2"]  
    version_aliases:  
      current: "9.2"  
    cc_api_version: v2  
  postgresql_node:  
    supported_versions: ["9.2"]  
    default_version: "9.2"  
    max_tmp: 900  
    password: "c1oudc0w"  # CHANGE  

  redis_gateway:  
    token: "c1oudc0w"  # CHANGE - the token you use later with `cf create-service-auth-token`  
    default_plan: default  
    supported_versions: ["2.6"]  
    version_aliases:  
      current: "2.6"  
    cc_api_version: v2  
  redis_node:  
    supported_versions: ["2.6"]  
    default_version: "2.6"  
    max_tmp: 900  

  rabbit_gateway:  
    token: "c1oudc0w"  # CHANGE - the token you use later with `cf create-service-auth-token`  
    default_plan: "default"  
    supported_versions: ["3.0"]  
    version_aliases:  
      current: "3.0"  
    cc_api_version: v2  
  rabbit_node:  
    supported_versions: ["3.0"]  
    default_version: "3.0"  
    max_tmp: 900  

---

When I deployed, there was a error
Error 400007: `services_contrib_gateway/0' is not running after update

and bosh vms:
| services_contrib_gateway/0 | failing | small         | 80.80.80.217 |

and there is no plan for cf create-service

root@ubuntu:~/bosh-workspace/deployments/cf-services# cf services -m
Getting services... OK

service         version   provider   plans   description  
blob            0.51      core               Blob store  
elasticsearch   0.20      core               Elasticsearch search service 
memcached       1.4       core               Memcached in-memory cache  
mongodb         2.2       core               MongoDB NoSQL database  
postgresql      9.2       core               PostgreSQL database (vFabric)
rabbitmq        3.0       core               RabbitMQ message queue  
redis           2.6       core               Redis key-value store
